const state={equipment:[],history:[],filtered:[],selected:null,lang:'vi',dueTab:'pm'};
const $=id=>document.getElementById(id);
const dict={vi:{subtitle:'Nhà Máy Biên Hòa - NANOCO / Bien Hoa Factory - NANOCO',refresh:'Làm mới',systemLabel:'HỆ THỐNG QUẢN LÝ THIẾT BỊ',heroTitle:'Dashboard thiết bị, lý lịch và lịch sử máy',heroText:'Dữ liệu đồng bộ từ 2 sheet: Equipment_Register và Asset_Event_Log1. Người dùng chỉ cần bấm Làm mới để cập nhật.',searchLabel:'Tìm kiếm nhanh',monthLabel:'Tháng báo cáo',areaLabel:'Khu vực',statusLabel:'Trạng thái',activityLabel:'Hoạt động',totalEq:'Tổng thiết bị',running:'Đang hoạt động',duePm:'Đến hạn PM',monthEvents:'Sự kiện tháng',breakdown:'Đang hư/dừng',disposal:'Chờ thanh lý',monthlyReport:'Báo cáo trong tháng',pmProgress:'Tiến độ bảo trì',upcoming:'Sắp tới hạn',next30:'30 ngày tới',calibration:'Hiệu chuẩn',inspection:'Kiểm định',attention:'Tình trạng cần chú ý',equipmentList:'Danh sách thiết bị',selectMachine:'Chọn một thiết bị để xem lý lịch 360°',selectMachineDesc:'Có thể tìm theo tên máy, model, serial, khu vực, hãng hoặc mã tài sản.',profile:'Lý lịch máy',history:'Lịch sử thiết bị',qr:'QR từng máy'},en:{subtitle:'Bien Hoa Factory - NANOCO / Nhà Máy Biên Hòa - NANOCO',refresh:'Refresh',systemLabel:'EQUIPMENT MANAGEMENT SYSTEM',heroTitle:'Equipment dashboard, profile and lifecycle history',heroText:'Data is synced from Equipment_Register and Asset_Event_Log1. Users only click Refresh to update.',searchLabel:'Quick search',monthLabel:'Report month',areaLabel:'Area',statusLabel:'Status',activityLabel:'Activity',totalEq:'Total equipment',running:'Running',duePm:'PM due',monthEvents:'Monthly events',breakdown:'Breakdown',disposal:'Waiting disposal',monthlyReport:'Monthly report',pmProgress:'PM progress',upcoming:'Upcoming due',next30:'Next 30 days',calibration:'Calibration',inspection:'Inspection',attention:'Attention',equipmentList:'Equipment list',selectMachine:'Select equipment to view 360° profile',selectMachineDesc:'Search by machine name, model, serial, area, maker, vendor or asset code.',profile:'Equipment profile',history:'Equipment history',qr:'Equipment QR'}};
function t(k){return dict[state.lang][k]||k}
function applyLang(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('langBtn').textContent=state.lang==='vi'?'EN':'VI';}
function norm(s){return (s??'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function parseDate(v){if(!v)return null;if(v instanceof Date)return v;let s=String(v).trim();let m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);let d=new Date(s);return isNaN(d)?null:d}
function fmtDate(v){let d=parseDate(v);return d?d.toLocaleDateString(state.lang==='vi'?'vi-VN':'en-GB'): (v||'-')}
function monthKey(d){d=parseDate(d);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:''}
function cycleMonths(txt){let s=norm(txt);let m=s.match(/(\d+)\s*(thang|month)/);return m?+m[1]:1}
function addMonths(d,n){let x=new Date(d);x.setMonth(x.getMonth()+n);return x}
function nextPmDate(eq){let months=cycleMonths(eq.pmCycle);let last=null;eventsFor(eq.id).forEach(h=>{if(isPM(h.type,h.description)){let d=parseDate(h.date);if(d&&(!last||d>last))last=d}});let base=last||parseDate(eq.installDate);if(!base)return null;let n=addMonths(base,months);let today=new Date();while(n<today)n=addMonths(n,months);return n}
function daysUntil(d){if(!d)return null;let today=new Date();today.setHours(0,0,0,0);let x=new Date(d);x.setHours(0,0,0,0);return Math.ceil((x-today)/86400000)}
function isPM(type,desc=''){let s=norm(type+' '+desc);return /pm|bao tri|bảo trì|maintenance|preventive/.test(s)}
function isRepair(type,desc=''){let s=norm(type+' '+desc);return /repair|sua|sửa|hu|hư|breakdown|corrective/.test(s)}
function isCal(type,desc=''){let s=norm(type+' '+desc);return /calibration|hieu chuan|hiệu chuẩn/.test(s)}
function isInspection(type,desc=''){let s=norm(type+' '+desc);return /inspection|kiem dinh|kiểm định|accreditation/.test(s)}
function statusClass(st){let s=norm(st);if(/breakdown|hu|dung|repair|sua/.test(s))return 'bad';if(/disposal|thanh ly|waiting/.test(s))return 'warn';return ''}
async function loadData(){try{let ts=Date.now();let [e,h]=await Promise.all([fetch(`data/equipment.json?v=${ts}`).then(r=>r.json()),fetch(`data/history.json?v=${ts}`).then(r=>r.json())]);state.equipment=e;state.history=h;postLoad();}catch(err){console.error(err);alert('Không đọc được dữ liệu JSON. Kiểm tra data/equipment.json và data/history.json.');}}
function postLoad(){fillFilters();applyFilters();updateDashboard();if(state.filtered[0])selectEquipment(state.filtered[0].id,false);}
function fillFilters(){let areas=[...new Set(state.equipment.map(x=>x.area).filter(Boolean))].sort();let statuses=[...new Set(state.equipment.map(x=>x.status||'Running'))].sort();$('areaFilter').innerHTML='<option value="">Tất cả khu vực</option>'+areas.map(x=>`<option>${x}</option>`).join('');$('statusFilter').innerHTML='<option value="">Tất cả trạng thái</option>'+statuses.map(x=>`<option>${x}</option>`).join('');$('activityFilter').innerHTML='<option value="">Tất cả hoạt động</option><option>PM</option><option>Repair</option><option>Calibration</option><option>Inspection</option><option>All Events</option>';let now=new Date();$('monthInput').value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;}
function allText(eq){return Object.values(eq).join(' ')}
function applyFilters(){let q=norm($('searchInput').value);let area=$('areaFilter').value;let st=$('statusFilter').value;state.filtered=state.equipment.filter(eq=>(!q||norm(allText(eq)).includes(q))&&(!area||eq.area===area)&&(!st||(eq.status||'Running')===st));renderList();updateDashboard();}
function eventsFor(id){return state.history.filter(h=>h.assetId===id || (h.assetId && state.equipment.find(e=>e.id===id)?.assetCode && h.assetId===state.equipment.find(e=>e.id===id)?.assetCode)).sort((a,b)=>(parseDate(b.date)||0)-(parseDate(a.date)||0));}
function renderList(){$('listCount').textContent=state.filtered.length;$('equipmentList').innerHTML=state.filtered.map(eq=>`<div class="eq-item ${state.selected===eq.id?'active':''}" onclick="selectEquipment('${eq.id.replace(/'/g,"\\'")}')"><h4>${eq.name}</h4><p>${eq.model||eq.parameter||'-'} · ${eq.area||'-'} · ${eq.manufacturer||'-'}</p><span class="badge ${statusClass(eq.status)}">${eq.status||'Running'}</span></div>`).join('')||'<div class="summaryBox">Không có dữ liệu</div>';}
function selectEquipment(id,scroll=true){state.selected=id;renderList();let eq=state.equipment.find(e=>e.id===id);if(!eq)return;$('emptyState').classList.add('hidden');let el=$('detailContent');el.classList.remove('hidden');let url=`${location.origin}${location.pathname}?id=${encodeURIComponent(eq.id)}`;let qr=`https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${encodeURIComponent(url)}`;let fields=[['No.',eq.no],['Mã tài sản',eq.assetCode],['Tên theo mã tài sản',eq.assetName],['Phân loại',eq.category],['Model',eq.model],['Serial',eq.serial],['Thông số kỹ thuật',eq.parameter],['Số lượng',eq.quantity],['Hãng SX',eq.manufacturer],['Nhà cung cấp',eq.vendor],['Năm sản xuất',eq.year],['Vị trí lắp đặt',eq.position],['Chu kỳ bảo dưỡng',eq.pmCycle],['Ngày lắp đặt',fmtDate(eq.installDate)],['Kiểm định',eq.inspection],['Hiệu chuẩn',eq.calibration],['Ghi chú',eq.note],['Next PM',fmtDate(nextPmDate(eq))]];
let hist=eventsFor(eq.id);el.innerHTML=`<div class="detail-hero"><div><h2>${eq.name}</h2><span class="badge ${statusClass(eq.status)}">${eq.status||'Running'}</span><p>${eq.model||eq.parameter||''} · ${eq.area||''}</p></div><div class="qrBox"><img src="${qr}" alt="QR"><div>${t('qr')}</div></div></div><h3 class="section-title">${t('profile')}</h3><div class="profile-grid">${fields.map(([k,v])=>`<div class="info"><label>${k}</label><b>${v||'-'}</b></div>`).join('')}</div><h3 class="section-title">${t('history')}</h3><div class="timeline">${hist.length?hist.map(h=>`<div class="event"><div class="event-head"><span>${h.type||'Other'}</span><span>${fmtDate(h.date)}</span></div><p>${h.description||'-'}</p><div class="event-meta">Result: ${h.result||'-'} · Owner: ${h.owner||'-'} · Downtime: ${h.downtime||'0'} phút · Cost: ${h.cost||'-'}</div></div>`).join(''):'<div class="summaryBox">Chưa có lịch sử</div>'}</div>`;if(scroll)document.getElementById('detailCard').scrollIntoView({behavior:'smooth',block:'start'});}
function updateDashboard(){let eq=state.filtered.length?state.filtered:state.equipment;let month=$('monthInput').value;let monthEvents=state.history.filter(h=>monthKey(h.date)===month);$('monthBadge').textContent=month;$('kpiTotal').textContent=state.equipment.length;$('kpiRunning').textContent=state.equipment.filter(e=>norm(e.status).includes('running')).length;let duePm=state.equipment.filter(e=>{let d=nextPmDate(e);let x=daysUntil(d);return x!==null&&x<=30}).length;$('kpiDuePm').textContent=duePm;$('kpiEvents').textContent=monthEvents.length;$('kpiBreakdown').textContent=state.equipment.filter(e=>statusClass(e.status)==='bad').length;$('kpiDisposal').textContent=state.equipment.filter(e=>norm(e.status).includes('disposal')||norm(e.status).includes('thanh')).length;renderMonthBars(monthEvents);renderPMProgress(monthEvents);renderDueList();renderAttention();}
function renderMonthBars(events){let defs=[['Bảo trì','PM',isPM],['Sửa chữa','Repair',isRepair],['Hiệu chuẩn','Calibration',isCal],['Kiểm định','Inspection',isInspection]];let max=Math.max(1,...defs.map(d=>events.filter(h=>d[2](h.type,h.description)).length));$('monthBars').innerHTML=defs.map(([vi,en,fn])=>{let n=events.filter(h=>fn(h.type,h.description)).length;return `<div class="bar-row"><span>${state.lang==='vi'?vi:en}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`}).join('');}
function renderPMProgress(events){let total=state.equipment.length;let done=new Set(events.filter(h=>isPM(h.type,h.description)).map(h=>h.assetId)).size;let pct=total?Math.round(done/total*100):0;$('pmPercent').textContent=pct+'%';$('pmProgressBar').style.width=pct+'%';$('pmSummary').innerHTML=`<b>Đã bảo trì: ${done}/${total}</b><br><span>Chưa bảo trì: ${Math.max(0,total-done)}</span>`;}
function dueItems(kind){return state.equipment.map(e=>{let d=kind==='pm'?nextPmDate(e):parseDate(kind==='calibration'?e.calibration:e.inspection);return {e,d,days:daysUntil(d)}}).filter(x=>x.days!==null&&x.days<=30).sort((a,b)=>a.days-b.days).slice(0,12)}
function renderDueList(){let arr=dueItems(state.dueTab);$('dueList').innerHTML=arr.length?arr.map(x=>`<div class="item"><strong>${x.e.name}</strong><small>${x.days<0?'Quá hạn':'Còn '+x.days+' ngày'} · ${fmtDate(x.d)} · ${x.e.area||'-'}</small></div>`).join(''):'<div class="item"><strong>Không có dữ liệu</strong></div>';}
function renderAttention(){let arr=state.equipment.filter(e=>statusClass(e.status)).slice(0,10);$('attentionList').innerHTML=arr.length?arr.map(e=>`<div class="item"><strong>${e.name}</strong><small>${e.status} · ${e.area||'-'}</small></div>`).join(''):'<div class="item"><strong>Không có dữ liệu</strong></div>';}
function init(){applyLang();$('refreshBtn').onclick=loadData;$('langBtn').onclick=()=>{state.lang=state.lang==='vi'?'en':'vi';applyLang();renderList();updateDashboard();if(state.selected)selectEquipment(state.selected,false)};['searchInput','areaFilter','statusFilter','activityFilter'].forEach(id=>$(id).addEventListener('input',applyFilters));$('monthInput').addEventListener('input',updateDashboard);document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.dueTab=b.dataset.due;renderDueList();});loadData();}
init();
